### ISSUE TITLE
Why do you require keys with lowercase and underscore only

### ISSUE THREAD

**Issue by Azbesciak** [keeyzar/flutterintl#1]
Can you please remove that requirement? I would like to have `camelCase`, arb does not restrict such a rule, and replacing it by hand is madness...

**Comment by keeyzar** [comment]
Hi Azbesciak, 

Thank you for the report! You're absolutely right.
If I'm not mistaken, it's simply a regex in the UI - should be done fairly quick!

**Comment by Azbesciak** [comment]
Thank you! Good job by the way

pon., 30 paź 2023, 10:47 użytkownik Kevin Kekule ***@***.***>
napisał:
